import java.nio.file.Paths
import org.apache.tools.ant.taskdefs.condition.Os

plugins {
    id 'net.fabricmc.fabric-loom-remap' version "${loom_version}"
    id 'maven-publish'
}

def commonProperties = new Properties()
file('../common/gradle.properties').withInputStream { commonProperties.load(it) }
ext.mod_version = commonProperties['mod_version']

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

repositories {
    // Add repositories to retrieve artifacts from in here.
    // You should only use this when depending on other mods because
    // Loom adds the essential maven repositories to download Minecraft and libraries from automatically.
    // See https://docs.gradle.org/current/userguide/declaring_repositories.html
    // for more information about repositories.
    maven {
        name = "Sponge"
        url = "https://repo.spongepowered.org/repository/maven-public/"
    }
}

loom {
    accessWidenerPath = file("src/main/resources/cheatutils.accesswidener")

    mixin {
        useLegacyMixinAp = true
        defaultRefmapName = "cheatutils-refmap.json"
    }
}

dependencies {
    // To change the versions see the gradle.properties file
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
    compileOnly "org.spongepowered:mixin:0.8.7"
    implementation "org.ow2.asm:asm:9.9"
    implementation "org.ow2.asm:asm-tree:9.9"

    annotationProcessor "net.fabricmc:sponge-mixin:0.17.2+mixin.0.8.7"
    annotationProcessor "org.ow2.asm:asm:9.9"
    annotationProcessor "org.ow2.asm:asm-tree:9.9"
    annotationProcessor "com.google.code.gson:gson:2.11.0"
    annotationProcessor "com.google.guava:guava:33.3.1-jre"
    annotationProcessor files('../mixin-plugin/annotation-processor/build/libs/annotation-processor.jar')
}

sourceSets {
    main {
        java {
            srcDir '../common/java'
            srcDir '../java-scripting-language/src/main/java'
            srcDir '../mixin-plugin/common/java'
        }
        resources {
            srcDir '../common/resources'
        }
    }
}

processResources {
    inputs.property "version", project.version

    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release.set(21)
}

java {
    // Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
    // if it is present.
    // If you remove this line, sources will not be generated.
    // withSourcesJar()

    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

jar {
    from("LICENSE") {
        rename { "${it}_${project.base.archivesName.get()}"}
    }

    exclude("net/caffeinemc/**")
    exclude("net/irisshaders/**")
    exclude("com/zergatul/cheatutils/utils/mappings/**")
}

tasks.withType(JavaCompile).configureEach {
    it.options.compilerArgs.add("-parameters")
    it.options.compilerArgs.addAll([
            "-processor",
            "com.zergatul.mixin.AnnotationProcessor,org.spongepowered.tools.obfuscation.MixinObfuscationProcessorInjection,org.spongepowered.tools.obfuscation.MixinObfuscationProcessorTargets"])
}

tasks.register('buildAnnotationProcessor', {
    doFirst {
        def annotationProcessorJar = file('../mixin-plugin/annotation-processor/build/libs/annotation-processor.jar')
        if (!annotationProcessorJar.exists()) {
            println 'Annotation processor JAR not found. Building annotation processor...'
            def buildResult = exec {
                def gradlew = Os.isFamily(Os.FAMILY_WINDOWS) ? 'gradlew.bat' : 'gradlew'
                commandLine "../mixin-plugin/annotation-processor/$gradlew", '-p', '../mixin-plugin/annotation-processor', 'build'
            }
            if (buildResult.exitValue != 0) {
                throw new GradleException('Failed to build the annotation processor project.')
            }
        }
    }
})

tasks.withType(JavaCompile).configureEach {
    dependsOn('buildAnnotationProcessor')
}


remapJar {
    afterEvaluate {
        archiveFileName = "$archives_base_name-$mod_version-fabric-${minecraft_version}.jar"
    }
}