plugins {
    id 'net.fabricmc.fabric-loom' version "${loom_version}"
    id 'cheatutils'
}

ext.mod_version = cheatutils.getModVersion()

group = project.maven_group
version = project.mod_version

base {
    archivesName = project.archives_base_name
}

loom {
    accessWidenerPath = file("src/main/resources/cheatutils.classtweaker")
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
    compileOnly("org.jspecify:jspecify:1.0.0")
}

sourceSets {
    main {
        java {
            srcDir '../common/java'
            srcDir '../common/forge-and-fabric/java'
            srcDir '../java-scripting-language/src/main/java'
            srcDir '../mixin-plugin/common/java'
        }
        resources {
            srcDir '../common/resources'
            srcDir '../common/forge-and-fabric/resources'
        }
    }
}

processResources {
    inputs.property "version", project.version

    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 25
    it.options.encoding = 'UTF-8'
    it.options.compilerArgs.add("-parameters")
}

java {
    //withSourcesJar()

    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

tasks.named('jar', Jar) {
    archiveFileName = "${base.archivesName.get()}-${project.mod_version}-fabric-${project.minecraft_version}.jar"

    from("LICENSE") {
        rename { "${it}_${project.archivesName.get()}"}
    }

    exclude("net/caffeinemc/**")
    exclude("net/irisshaders/**")
}