# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Fabric Properties
	# check these on https://fabricmc.net/develop
	minecraft_version=1.21.1
	loader_version=0.19.2
	loom_version=1.16-SNAPSHOT

# Mod Properties
	# mod_version = 0.0.0 - loaded from common directory
	maven_group = com.zergatul.cheatutils
	archives_base_name = cheatutils

# Dependencies
	fabric_api_version=0.116.12+1.21.1