# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.1
loader_version=0.18.4
loom_version=1.15-SNAPSHOT

# Mod Properties
# mod_version = 0.0.0 - loaded from common directory
maven_group = com.zergatul.cheatutils
archives_base_name = cheatutils

# Dependencies
fabric_version=0.144.0+26.1