# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.3-pre-2
loader_version=0.19.5
loom_version=1.17-SNAPSHOT

# Mod Properties
# mod_version = 0.0.0 - loaded from common directory
maven_group = com.zergatul.cheatutils
archives_base_name = cheatutils

# Dependencies
fabric_version=0.159.4+26.3