mod_id=cheatutils
mod_name=CheatUtils
mod_group=com.zergatul.cheatutils
mod_version=3.0.1
mod_description=Open http://localhost:5005/ in your browser to access mod settings.
minecraft_version=1.12.2
forge_version=14.23.5.2860
mappings_channel=snapshot
mappings_version=20180814-1.12
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false