plugins {
    id 'java'
    id 'eclipse'
    id 'idea'
    id 'net.minecraftforge.gradle' version '[7.0.18,8)'
    id 'cheatutils'
}

def modVersion = cheatutils.getModVersion()
def commonMixinsConfigOriginal = 'cheatutils.common.mixins.json'
def commonMixinsConfigForge = 'cheatutils.common-forge-patched.mixins.json'
def generatedMixinsConfigDir = layout.buildDirectory.dir('generated/forge-mixins/resources')

group = mod_group_id
version = modVersion

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

minecraft {
    accessTransformer = 'META-INF/forge_at.cfg'
    runs {
        client {
            workingDir = layout.projectDirectory.dir('run')
            args "-mixin.config=${commonMixinsConfigForge}"
            //args "-mixin.config=cheatutils.iris.mixins.json"
            args "-mixin.config=cheatutils.forge.mixins.json"
            systemProperty 'forge.logging.console.level', 'debug'
        }
    }
}

repositories {
    minecraft.mavenizer(it)
    maven fg.forgeMaven
    maven fg.minecraftLibsMaven
}

tasks.register('generateForgeMixinsConfig', Copy) {
    from('../common/resources') {
        include commonMixinsConfigOriginal
        filter { String line -> line.replace("JAVA_25", "JAVA_21") }
        rename { commonMixinsConfigForge }
    }
    into generatedMixinsConfigDir
}

sourceSets {
    main {
        java {
            srcDir '../common/java'
            srcDir '../java-scripting-language/src/main/java'
            srcDir '../mixin-plugin/common/java'
        }
        resources {
            srcDir '../common/resources'
            exclude commonMixinsConfigOriginal
            srcDir generatedMixinsConfigDir
        }
    }
}

dependencies {
    implementation minecraft.dependency("net.minecraftforge:forge:${minecraft_version}-${forge_version}")
}

tasks.named('processResources', ProcessResources) {
    dependsOn tasks.named('generateForgeMixinsConfig')

    var replaceProperties = [
            minecraft_version: minecraft_version, minecraft_version_range: minecraft_version_range,
            forge_version: forge_version, forge_version_range: forge_version_range,
            loader_version_range: loader_version_range,
            mod_id: mod_id, mod_name: mod_name, mod_license: mod_license, mod_version: modVersion,
            mod_authors: mod_authors, mod_description: mod_description,
    ]
    inputs.properties replaceProperties

    filesMatching(['META-INF/mods.toml', 'pack.mcmeta']) {
        expand replaceProperties + [project: project]
    }

}

tasks.named('jar', Jar) {
    archiveFileName = "$mod_id-$modVersion-forge-${minecraft_version}.jar"

    includeEmptyDirs = false
    exclude("net/caffeinemc/**")
    exclude("net/irisshaders/**")

    manifest {
        attributes([
                // excluded "cheatutils.iris.mixins.json"
                "MixinConfigs": "${commonMixinsConfigForge},cheatutils.forge.mixins.json"
        ])
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 25
    it.options.encoding = 'UTF-8'
    it.options.compilerArgs.add("-parameters")
}

idea.module { downloadJavadoc = downloadSources = true }