net.minecraftforge.gradle.merge-source-sets=true

minecraft_version=26.2
minecraft_version_range=[26.2,)
forge_version=65.0.0
forge_version_range=[65.0.0,)
loader_version_range=[65,)

mod_id=cheatutils
mod_name=CheatUtils
mod_license=MIT
# mod_version = 0.0.0 - loaded from common directory
mod_group_id=com.zergatul.cheatutils
mod_authors=Zergatul, SomeRandomDude-a
mod_description=Open http://localhost:5005/ in your browser to access mod settings.\nIf you run multiple minecraft instances, use http://localhost:5006/, http://localhost:5007/ and so on.\nYou can find tutorial videos on curseforge page: https://www.curseforge.com/minecraft/mc-mods/cheatutils\nSource code: https://github.com/Zergatul/cheatutils