/* Generated By:JJTree: Do not edit this line. ASTExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.zergatul.cheatutils.scripting;

public
class ASTExpression extends SimpleNode {
  public ASTExpression(int id) {
    super(id);
  }

  public ASTExpression(ScriptingLanguage p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f6c63fbe1d762213d3e808c6d2674016 (do not edit this line) */
