/* Generated By:JJTree: Do not edit this line. ASTFloatingPointLiteral.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.zergatul.cheatutils.scripting;

public
class ASTFloatingPointLiteral extends SimpleNode {
  public ASTFloatingPointLiteral(int id) {
    super(id);
  }

  public ASTFloatingPointLiteral(ScriptingLanguage p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=6e3ecada5ba2abea2835437f737dac8f (do not edit this line) */
