/* Generated By:JJTree: Do not edit this line. ASTMethodCall.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.zergatul.cheatutils.scripting;

public
class ASTMethodCall extends SimpleNode {
  public ASTMethodCall(int id) {
    super(id);
  }

  public ASTMethodCall(ScriptingLanguage p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8d5a1bb9df3782b3af687e1f2a1403f3 (do not edit this line) */
