/* Generated By:JavaCC: Do not edit this line. ScriptingLanguageTreeConstants.java Version 5.0 */
package com.zergatul.cheatutils.scripting;

public interface ScriptingLanguageTreeConstants
{
  public int JJTINPUT = 0;
  public int JJTSTATEMENT = 1;
  public int JJTEMPTYSTATEMENT = 2;
  public int JJTBLOCKSTATEMENT = 3;
  public int JJTIFSTATEMENT = 4;
  public int JJTMETHODCALL = 5;
  public int JJTEXPRESSION = 6;
  public int JJTARGUMENTS = 7;
  public int JJTNAME = 8;
  public int JJTIDENTIFIER = 9;
  public int JJTLITERAL = 10;
  public int JJTSTRINGLITERAL = 11;
  public int JJTBOOLEANLITERAL = 12;
  public int JJTNULLLITERAL = 13;


  public String[] jjtNodeName = {
    "Input",
    "Statement",
    "EmptyStatement",
    "BlockStatement",
    "IfStatement",
    "MethodCall",
    "Expression",
    "Arguments",
    "Name",
    "Identifier",
    "Literal",
    "StringLiteral",
    "BooleanLiteral",
    "NullLiteral",
  };
}
/* JavaCC - OriginalChecksum=d14cb8ae6bbdd1ce9ccee390ca635f13 (do not edit this line) */
