package com.zergatul.cheatutils.scripting;

import com.zergatul.cheatutils.common.ModLoaderBridge;
import com.zergatul.cheatutils.common.ModLoaderBridgeInstance;
import com.zergatul.cheatutils.utils.ModMetadata;
import com.zergatul.cheatutils.utils.ResourceHelper;
import com.zergatul.scripting.type.*;
import com.zergatul.scripting.type.operation.BinaryOperation;
import com.zergatul.scripting.type.operation.IndexOperation;
import com.zergatul.scripting.type.operation.UnaryOperation;
import net.minecraft.SharedConstants;
import org.apache.commons.io.IOUtils;

import java.io.IOException;
import java.io.InputStream;
import java.lang.reflect.Modifier;
import java.nio.charset.StandardCharsets;
import java.util.*;

public class ApiDocsGenerator {

    public static List<String> generateLines() {
        return generateLines(true);
    }

    public static List<String> generateLines(boolean includeScriptTypeDescriptions) {
        List<String> lines = new ArrayList<>();
        ModLoaderBridge bridge = ModLoaderBridgeInstance.get();

        Map<String, String> commits = ModMetadata.getCommitsSafe();
        lines.add("// ==========================================");
        lines.add("// CheatUtils Scripting API Definitions (autogenerated)");
        lines.add("// Context: Minecraft Mod");
        lines.add(String.format("// Minecraft Version: %s (%s)", SharedConstants.getCurrentVersion().name(), bridge.getModLoaderName()));
        lines.add(String.format("// CheatUtils Version: %s", bridge.getModVersion()));
        lines.add(String.format("// CheatUtils Source: https://github.com/Zergatul/cheatutils @ %s", commits.get("cheatutils")));
        lines.add(String.format("// Scripting Language Source: https://github.com/Zergatul/java-scripting-language @ %s", commits.get("java-scripting-language")));
        lines.add("// ==========================================");

        lines.add("");
        lines.add("// --- Script Types ---");
        for (ScriptType type : ScriptType.values()) {
            lines.add("");
            lines.add("/*");
            lines.add(
                    String.format(
                            "* module : %s / signature : %s / allowed ApiType's : [%s]",
                            type.getModuleName(),
                            SFunctionalInterface.from(type.createParameters().getFunctionalInterface()),
                            String.join(", ", Arrays.stream(type.getApis()).map(Enum::name).toList())));

            if (includeScriptTypeDescriptions) {
                InputStream stream = ResourceHelper.get("llm/script-types/" + type);
                if (stream != null) {
                    try (stream) {
                        String content = IOUtils.toString(stream, StandardCharsets.UTF_8);
                        for (String line : extractLines(content)) {
                            lines.add("* " + line);
                        }
                    } catch (IOException e) {
                        // do nothing
                    }
                }
            }
            lines.add("*/");
        }

        lines.add("");
        lines.add("// --- Primitive Types ---");

        for (SType type : getPrimitiveTypes()) {
            lines.add("");
            buildType(lines, type);
        }

        lines.add("");
        lines.add("// --- Custom Types ---");
        for (Class<?> clazz : ScriptType.EVENTS.createParameters().getCustomTypes()) {
            lines.add("");
            buildType(lines, SType.fromJavaType(clazz));
        }

        List<PropertyReference> apis = SType.fromJavaType(Root.class).getStaticProperties();

        lines.add("");
        lines.add("// --- Available APIs ---");
        lines.add("");
        for (PropertyReference property : apis) {
            lines.add(String.format("static %s %s { get; }", formatType(property.getType()), property.getName()));
        }

        lines.add("");
        lines.add("// --- API Types ---");

        //ScriptType scriptType = ScriptType.valueOf(id);

        List<Class<?>> baseClasses = new ArrayList<>();
        for (PropertyReference property : apis)  {
            Class<?> baseClass = property.getType().getJavaClass().getSuperclass();
            if (baseClass != Object.class && !baseClasses.contains(baseClass)) {
                baseClasses.add(baseClass);
            }
        }

        baseClasses.sort(Comparator.comparing(Class::getName));
        for (Class<?> clazz : baseClasses) {
            lines.add("");
            buildType(lines, SType.fromJavaType(clazz));
        }

        for (SType type : apis.stream().map(PropertyReference::getType).sorted(Comparator.comparing(ApiDocsGenerator::formatType)).toList()) {
            lines.add("");
            buildType(lines, type);
        }

        return lines;
    }

    private static void buildType(List<String> lines, SType type) {
        Class<?> baseClass = type.getJavaClass().getSuperclass();
        lines.add(
                String.format("%s%s %s%s {",
                        type.isAbstract() ? "abstract " : "",
                        type instanceof SValueType ? "struct" : "class",
                        formatType(type),
                        baseClass != null && baseClass != Object.class ? " : " + formatType(SType.fromJavaType(type.getJavaClass().getSuperclass())) : ""));

        for (PropertyReference property : type.getStaticProperties()) {
            lines.add(String.format("\tstatic %s %s { %s%s }", property.getType(), property.getName(), property.canLoad() ? "get;" : "", property.canStore() ? "set;" : ""));
        }
        for (MethodReference method : type.getStaticMethods()) {
            formatMethod(lines, "static ", method);
        }
        for (ConstructorReference constructor : type.getConstructors()) {
            lines.add(String.format("\tconstructor(%s);", formatParameters(constructor.getParameters())));
        }
        for (PropertyReference property : type.getInstanceProperties()) {
            lines.add(String.format("\t%s %s { %s%s }", formatType(property.getType()), property.getName(), property.canLoad() ? "get;" : "", property.canStore() ? "set;" : ""));
        }
        for (MethodReference method : type.getDeclaredInstanceMethods()) {
            formatMethod(lines, "", method);
        }
        for (IndexOperation operation : type.getIndexOperations()) {
            lines.add(String.format("\t%s this[%s index] { %s%s }", operation.returnType, operation.indexType, operation.canGet() ? "get;" : "", operation.canSet() ? "set;" : ""));
        }
        for (UnaryOperation operation : type.getUnaryOperations()) {
            lines.add(String.format("\toperator [%s] %s(%s arg);", operation.getOperator(), operation.getResultType(), operation.getOperandType()));
        }
        for (BinaryOperation operation : type.getBinaryOperations()) {
            if (operation.getLeft() == SJavaObject.instance && operation.getRight() == SJavaObject.instance) {
                continue;
            }
            lines.add(String.format("\toperator [%s] %s(%s left, %s right);", operation.getOperator(), operation.getResultType(), operation.getLeft(), operation.getRight()));
        }

        if (type instanceof SClassType) {
            for (Class<?> nested : type.getJavaClass().getDeclaredClasses()) {
                if (Modifier.isPublic(nested.getModifiers())) {
                    int position1 = lines.size();
                    buildType(lines, SType.fromJavaType(nested));
                    int position2 = lines.size();
                    for (int i = position1; i < position2; i++) {
                        lines.set(i, "\t" + lines.get(i));
                    }
                }
            }
        }

        lines.add("}");
    }

    private static void formatMethod(List<String> lines, String prefix, MethodReference method) {
        method.getDescription().ifPresent(description -> {
            String[] lines2 = extractLines(description);
            if (lines2.length == 1) {
                lines.add(String.format("\t/* %s */", lines2[0]));
            } else {
                lines.add("\t/*");
                for (String line : lines2) {
                    lines.add(String.format("\t* %s", line));
                }
                lines.add("\t*/");
            }
        });
        if (method instanceof NativeMethodReference nativeMethod) {
            ApiVisibility visibility = nativeMethod.getUnderlying().getAnnotation(ApiVisibility.class);
            if (visibility != null) {
                lines.add(String.format("\t@ApiVisibility(%s)", String.join(", ", Arrays.stream(visibility.value()).map(ApiType::name).toList())));
            }
        }
        lines.add(String.format("\t%s%s %s(%s);", prefix, method.getReturn(), method.getName(), formatParameters(method.getParameters())));
    }

    private static String formatParameters(List<MethodParameter> parameters) {
        StringBuilder builder = new StringBuilder();
        for (int i = 0; i < parameters.size(); i++) {
            builder.append(parameters.get(i).type());
            builder.append(' ');
            builder.append(parameters.get(i).name());
            if (i < parameters.size() - 1) {
                builder.append(", ");
            }
        }
        return builder.toString();
    }

    private static String formatType(SType type) {
        if (type instanceof SClassType classType) {
            Class<?> clazz = classType.getJavaClass();
            if (clazz.getPackageName().startsWith("com.zergatul.cheatutils.scripting.")) {
                return clazz.getName().substring(clazz.getPackageName().length() + 1);
            }
        }
        return type.toString();
    }

    private static List<SType> getPrimitiveTypes() {
        return List.of(
                SBoolean.instance,
                SInt8.instance,
                SInt16.instance,
                SInt.instance,
                SInt64.instance,
                SFloat32.instance,
                SFloat.instance,
                SChar.instance,
                SString.instance);
    }

    private static String[] extractLines(String str) {
        return str.split("\\r?\\n");
    }
}