package com.zergatul.cheatutils.scripting;

import com.zergatul.cheatutils.common.ModLoaderBridge;
import com.zergatul.cheatutils.common.ModLoaderBridgeInstance;
import com.zergatul.cheatutils.utils.ModMetadata;
import com.zergatul.cheatutils.utils.ResourceHelper;
import com.zergatul.scripting.compiler.CompilationParameters;
import com.zergatul.scripting.formatting.TypeDisplayFormatter;
import com.zergatul.scripting.parser.BinaryOperator;
import com.zergatul.scripting.type.*;
import com.zergatul.scripting.type.operation.BinaryOperation;
import com.zergatul.scripting.type.operation.IndexOperation;
import com.zergatul.scripting.type.operation.UnaryOperation;
import net.minecraft.SharedConstants;
import org.apache.commons.io.IOUtils;

import java.io.IOException;
import java.io.InputStream;
import java.lang.reflect.Modifier;
import java.nio.charset.StandardCharsets;
import java.util.*;

public class ApiDocsGenerator {

    private static final String SCRIPTING_PACKAGE = "com.zergatul.cheatutils.scripting";
    private static final TypeDisplayFormatter TYPE_FORMATTER = new TypeDisplayFormatter(clazz -> {
        String packageName = clazz.getPackageName();
        if (packageName.equals(SCRIPTING_PACKAGE) || packageName.startsWith(SCRIPTING_PACKAGE + ".")) {
            return clazz.getSimpleName();
        }
        return "Java<" + clazz.getName() + ">";
    });

    public static List<String> generateLines() {
        return generateLines(true);
    }

    public static List<String> generateLines(boolean includeScriptTypeDescriptions) {
        List<String> lines = new ArrayList<>();
        ModLoaderBridge bridge = ModLoaderBridgeInstance.get();

        Map<String, String> commits = ModMetadata.getCommitsSafe();
        lines.add("// ==========================================");
        lines.add("// CheatUtils Scripting API Definitions (autogenerated)");
        lines.add("// Context: Minecraft Mod");
        lines.add(String.format("// Minecraft Version: %s (%s)", SharedConstants.getCurrentVersion().name(), bridge.getModLoaderName()));
        lines.add(String.format("// CheatUtils Version: %s", bridge.getModVersion()));
        lines.add(String.format("// CheatUtils Source: https://github.com/Zergatul/cheatutils @ %s", commits.get("cheatutils")));
        lines.add(String.format("// Scripting Language Source: https://github.com/Zergatul/java-scripting-language @ %s", commits.get("java-scripting-language")));
        lines.add("// ==========================================");

        lines.add("");
        lines.add("// --- Script Types ---");
        for (ScriptType type : ScriptType.values()) {
            if (type == ScriptType.EXPR_EVAL) {
                continue;
            }

            CompilationParameters compilationParameters = ScriptCompilerRegistry.INSTANCE.getParameters(type);
            lines.add("");
            lines.add("/*");
            lines.add(
                    String.format(
                            "* module : %s / signature : %s / allowed ApiType's : [%s]",
                            type.getModuleName(),
                            SFunctionalInterface.from(compilationParameters.getFunctionalInterface()),
                            String.join(", ", Arrays.stream(type.getApis()).map(Enum::name).toList())));

            if (includeScriptTypeDescriptions) {
                InputStream stream = ResourceHelper.get("llm/script-types/" + type);
                if (stream != null) {
                    try (stream) {
                        String content = IOUtils.toString(stream, StandardCharsets.UTF_8);
                        for (String line : extractLines(content)) {
                            lines.add("* " + line);
                        }
                    } catch (IOException e) {
                        // do nothing
                    }
                }
            }
            lines.add("*/");
        }

        lines.add("");
        lines.add("// --- Primitive Types ---");

        for (SType type : getPrimitiveTypes()) {
            lines.add("");
            buildType(lines, type);
        }

        lines.add("");
        lines.add("// --- Custom Types ---");
        for (Class<?> clazz : ScriptCompilerRegistry.INSTANCE.getParameters(ScriptType.EVENTS).getCustomTypes()) {
            lines.add("");
            buildType(lines, SType.fromJavaType(clazz));
        }

        List<PropertyReference> apis = SType.fromJavaType(Root.class).getStaticProperties();

        lines.add("");
        lines.add("// --- Available APIs ---");
        lines.add("");
        for (PropertyReference property : apis) {
            formatDescription(lines, "", property.getDescription());
            lines.add(String.format("static %s %s { get; }", formatType(property.getType()), property.getName()));
        }

        lines.add("");
        lines.add("// --- API Types ---");

        //ScriptType scriptType = ScriptType.valueOf(id);

        List<Class<?>> baseClasses = new ArrayList<>();
        for (PropertyReference property : apis)  {
            Class<?> baseClass = property.getType().getJavaClass().getSuperclass();
            if (baseClass != Object.class && !baseClasses.contains(baseClass)) {
                baseClasses.add(baseClass);
            }
        }

        baseClasses.sort(Comparator.comparing(Class::getName));
        for (Class<?> clazz : baseClasses) {
            lines.add("");
            buildType(lines, SType.fromJavaType(clazz));
        }

        for (SType type : apis.stream().map(PropertyReference::getType).sorted(Comparator.comparing(ApiDocsGenerator::formatType)).toList()) {
            lines.add("");
            buildType(lines, type);
        }

        return lines;
    }

    private static void buildType(List<String> lines, SType type) {
        if (type instanceof SClassType classType) {
            if (classType.getJavaClass().isAnnotationPresent(AdvancedApi.class)) {
                lines.add("@AdvancedApi");
            }
        }

        Class<?> baseClass = type.getJavaClass().getSuperclass();
        lines.add(
                String.format("%s%s %s%s {",
                        type.isAbstract() ? "abstract " : "",
                        type instanceof SValueType ? "struct" : "class",
                        formatType(type),
                        baseClass != null && baseClass != Object.class ? " : " + formatType(SType.fromJavaType(type.getJavaClass().getSuperclass())) : ""));

        for (PropertyReference property : sortedProperties(type.getStaticProperties())) {
            formatProperty(lines, "static ", property);
        }
        for (MethodReference method : sortedMethods(type.getStaticMethods())) {
            formatMethod(lines, "static ", method);
        }
        if (shouldIncludeConstructors(type)) {
            for (ConstructorReference constructor : type.getConstructors()) {
                lines.add(String.format("\tconstructor(%s);", formatParameters(constructor.getParameters())));
            }
        }
        for (PropertyReference property : sortedProperties(type.getInstanceProperties())) {
            formatProperty(lines, "", property);
        }
        for (MethodReference method : sortedMethods(type.getDeclaredInstanceMethods())) {
            formatMethod(lines, "", method);
        }
        for (IndexOperation operation : type.getIndexOperations()) {
            lines.add(String.format(
                    "\t%s this[%s index] %s",
                    formatType(operation.returnType),
                    formatType(operation.indexType),
                    formatGetSet(operation.canGet(), operation.canSet())));
        }
        for (UnaryOperation operation : type.getUnaryOperations()) {
            lines.add(String.format(
                    "\toperator [%s] %s(%s arg);",
                    operation.getOperator(),
                    formatType(operation.getResultType()),
                    formatType(operation.getOperandType())));
        }
        for (BinaryOperation operation : type.getBinaryOperations()) {
            if (operation.getLeft() == SJavaObject.instance && operation.getRight() == SJavaObject.instance) {
                continue;
            }
            if (operation.getOperator() == BinaryOperator.NULL_COALESCING) {
                continue;
            }
            lines.add(String.format(
                    "\toperator [%s] %s(%s left, %s right);",
                    operation.getOperator(),
                    formatType(operation.getResultType()),
                    formatType(operation.getLeft()),
                    formatType(operation.getRight())));
        }

        if (type instanceof SClassType) {
            for (Class<?> nested : type.getJavaClass().getDeclaredClasses()) {
                if (Modifier.isPublic(nested.getModifiers())) {
                    int position1 = lines.size();
                    buildType(lines, SType.fromJavaType(nested));
                    int position2 = lines.size();
                    for (int i = position1; i < position2; i++) {
                        lines.set(i, "\t" + lines.get(i));
                    }
                }
            }
        }

        lines.add("}");
    }

    private static List<PropertyReference> sortedProperties(List<PropertyReference> properties) {
        return properties.stream().sorted(Comparator.comparing(PropertyReference::getName)).toList();
    }

    private static List<MethodReference> sortedMethods(List<MethodReference> properties) {
        return properties.stream().sorted(
                Comparator.comparing(MethodReference::getName).
                        thenComparing(ref -> ref.getParameters().size()))
                .toList();
    }

    private static void formatProperty(List<String> lines, String prefix, PropertyReference property) {
        if (!property.isPublic()) {
            return;
        }

        formatDescription(lines, "\t", property.getDescription());
        lines.add(String.format("\t%s%s %s %s", prefix, formatType(property.getType()), property.getName(), formatGetSet(property.canLoad(), property.canStore())));
    }

    private static void formatMethod(List<String> lines, String prefix, MethodReference method) {
        if (!method.isPublic()) {
            return;
        }

        if (method instanceof NativeMethodReference nativeMethod) {
            if (nativeMethod.getUnderlying().isAnnotationPresent(HiddenMethod.class)) {
                return;
            }
        }

        formatDescription(lines, "\t", method.getDescription());
        if (method instanceof NativeMethodReference nativeMethod) {
            if (nativeMethod.getUnderlying().isAnnotationPresent(AdvancedApi.class)) {
                lines.add("\t@AdvancedApi");
            }

            ApiVisibility visibility = nativeMethod.getUnderlying().getAnnotation(ApiVisibility.class);
            if (visibility != null) {
                lines.add(String.format("\t@ApiVisibility(%s)", String.join(", ", Arrays.stream(visibility.value()).map(ApiType::name).toList())));
            }
        }
        lines.add(String.format("\t%s%s %s(%s);", prefix, formatType(method.getReturn()), method.getName(), formatParameters(method.getParameters())));
    }

    private static void formatDescription(List<String> lines, String indent, Optional<String> description) {
        description.ifPresent(value -> {
            String[] lines2 = extractLines(value);
            if (lines2.length == 1) {
                lines.add(String.format("%s/* %s */", indent, lines2[0]));
            } else {
                lines.add(indent + "/*");
                for (String line : lines2) {
                    lines.add(String.format("%s* %s", indent, line));
                }
                lines.add(indent + "*/");
            }
        });
    }

    private static String formatParameters(List<MethodParameter> parameters) {
        StringBuilder builder = new StringBuilder();
        for (int i = 0; i < parameters.size(); i++) {
            builder.append(formatType(parameters.get(i).type()));
            builder.append(' ');
            builder.append(parameters.get(i).name());
            if (i < parameters.size() - 1) {
                builder.append(", ");
            }
        }
        return builder.toString();
    }

    private static String formatType(SType type) {
        return TYPE_FORMATTER.format(type);
    }

    private static boolean shouldIncludeConstructors(SType type) {
        if (type instanceof SClassType classType) {
            Class<?> clazz = classType.getJavaClass();
            return !clazz.getPackageName().startsWith("com.zergatul.cheatutils.scripting.modules");
        } else {
            return true;
        }
    }

    private static List<SType> getPrimitiveTypes() {
        return List.of(
                SBoolean.instance,
                SInt8.instance,
                SInt16.instance,
                SInt.instance,
                SInt64.instance,
                SFloat32.instance,
                SFloat.instance,
                SChar.instance,
                SString.instance);
    }

    private static String formatGetSet(boolean canGet, boolean canSet) {
        if (canGet && canSet) {
            return "{ get; set; }";
        }
        if (canGet) {
            return  "{ get; }";
        }
        if (canSet) {
            return "{ set; }";
        }
        return "<error>";
    }

    private static String[] extractLines(String str) {
        return str.split("\\r?\\n");
    }
}