package com.zergatul.cheatutils.scripting;

import com.zergatul.cheatutils.common.ModLoaderBridge;
import com.zergatul.cheatutils.common.ModLoaderBridgeInstance;
import com.zergatul.cheatutils.scripting.api.ApiType;
import com.zergatul.cheatutils.scripting.api.ApiVisibility;
import com.zergatul.cheatutils.scripting.api.Root;
import com.zergatul.cheatutils.utils.ModMetadata;
import com.zergatul.scripting.compiler.CompilationParameters;
import com.zergatul.scripting.formatting.TypeDisplayFormatter;
import com.zergatul.scripting.parser.BinaryOperator;
import com.zergatul.scripting.type.*;
import com.zergatul.scripting.type.operation.BinaryOperation;
import com.zergatul.scripting.type.operation.IndexOperation;
import com.zergatul.scripting.type.operation.UnaryOperation;
import net.minecraft.SharedConstants;
import org.apache.commons.io.IOUtils;

import java.io.IOException;
import java.io.InputStream;
import java.lang.reflect.Modifier;
import java.nio.charset.StandardCharsets;
import java.util.*;

public class ApiDocsGenerator {

    private static final String SCRIPTING_PACKAGE = "com.zergatul.cheatutils.scripting";
    private static final TypeDisplayFormatter TYPE_FORMATTER = new TypeDisplayFormatter(clazz -> {
        String packageName = clazz.getPackageName();
        if (packageName.equals(SCRIPTING_PACKAGE) || packageName.startsWith(SCRIPTING_PACKAGE + ".")) {
            return clazz.getSimpleName();
        }
        return "Java<" + clazz.getName() + ">";
    });

    public static List<String> generateLines() {
        List<String> lines = new ArrayList<>();
        ModLoaderBridge bridge = ModLoaderBridgeInstance.get();

        lines.add("// ==========================================");
        lines.add("// CheatUtils Scripting API Definitions (autogenerated)");
        lines.add("// Context: Minecraft Mod");
        lines.add(String.format("// Minecraft Version: %s (%s)", SharedConstants.getCurrentVersion().getName(), bridge.getModLoaderName()));
        lines.add(String.format("// CheatUtils Version: %s", bridge.getModVersion()));
        Map<String, String> commits = ModMetadata.getCommitsSafe();
        addSourceLine(lines, "CheatUtils", "https://github.com/Zergatul/cheatutils", commits.get("cheatutils"));
        addSourceLine(lines, "Scripting Language", "https://github.com/Zergatul/java-scripting-language", commits.get("java-scripting-language"));
        lines.add("// ==========================================");

        lines.add("");
        lines.add("// --- Script Types ---");
        for (ScriptType type : ScriptType.values()) {
            CompilationParameters parameters = ScriptCompilerRegistry.INSTANCE.getParameters(type);
            lines.add("");
            lines.add("/*");
            lines.add(String.format(
                    "* module : %s / signature : %s / allowed ApiType's : [%s]",
                    type.getModuleName(),
                    SFunctionalInterface.from(parameters.getFunctionalInterface()),
                    String.join(", ", Arrays.stream(type.getApis()).map(Enum::name).toList())));
            appendScriptTypeDescription(lines, type);
            lines.add("*/");
        }

        lines.add("");
        lines.add("// --- Primitive Types ---");
        for (SType type : getPrimitiveTypes()) {
            lines.add("");
            buildType(lines, type);
        }

        lines.add("");
        lines.add("// --- Custom Types ---");
        for (Class<?> clazz : ScriptCompilerRegistry.INSTANCE.getParameters(ScriptType.EVENTS).getCustomTypes()) {
            lines.add("");
            buildType(lines, SType.fromJavaType(clazz));
        }

        List<PropertyReference> apis = getStaticProperties(SType.fromJavaType(Root.class));
        lines.add("");
        lines.add("// --- Available APIs ---");
        lines.add("");
        for (PropertyReference property : apis) {
            formatDescription(lines, "", property.getDescription());
            lines.add(String.format("static %s %s { get; }", formatType(property.getType()), property.getName()));
        }

        lines.add("");
        lines.add("// --- API Types ---");
        List<Class<?>> baseClasses = new ArrayList<>();
        for (PropertyReference property : apis) {
            Class<?> baseClass = property.getType().getJavaClass().getSuperclass();
            if (baseClass != null && baseClass != Object.class && !baseClasses.contains(baseClass)) {
                baseClasses.add(baseClass);
            }
        }
        baseClasses.sort(Comparator.comparing(Class::getName));
        for (Class<?> clazz : baseClasses) {
            lines.add("");
            buildType(lines, SType.fromJavaType(clazz));
        }
        for (SType type : apis.stream().map(PropertyReference::getType).sorted(Comparator.comparing(ApiDocsGenerator::formatType)).toList()) {
            lines.add("");
            buildType(lines, type);
        }

        return lines;
    }

    private static void addSourceLine(List<String> lines, String name, String url, String commit) {
        lines.add(String.format("// %s Source: %s%s", name, url, commit == null || commit.isBlank() ? "" : " @ " + commit));
    }

    private static void appendScriptTypeDescription(List<String> lines, ScriptType type) {
        try (InputStream stream = ApiDocsGenerator.class.getClassLoader().getResourceAsStream("llm/script-types/" + type)) {
            if (stream == null) {
                return;
            }
            String content = IOUtils.toString(stream, StandardCharsets.UTF_8);
            for (String line : extractLines(content)) {
                lines.add("* " + line);
            }
        } catch (IOException ignored) {
        }
    }

    private static void buildType(List<String> lines, SType type) {
        Class<?> javaClass = type.getJavaClass();
        Class<?> baseClass = javaClass == null ? null : javaClass.getSuperclass();
        lines.add(String.format(
                "%s%s %s%s {",
                type.isAbstract() ? "abstract " : "",
                type instanceof SValueType ? "struct" : "class",
                formatType(type),
                baseClass != null && baseClass != Object.class ? " : " + formatType(SType.fromJavaType(baseClass)) : ""));

        for (PropertyReference property : sortedProperties(getStaticProperties(type))) {
            formatProperty(lines, "static ", property);
        }
        for (MethodReference method : sortedMethods(getStaticMethods(type))) {
            formatMethod(lines, "static ", method);
        }
        if (shouldIncludeConstructors(type)) {
            for (ConstructorReference constructor : type.getConstructors()) {
                lines.add(String.format("\tconstructor(%s);", formatParameters(constructor.getParameters())));
            }
        }
        for (PropertyReference property : sortedProperties(getInstanceProperties(type))) {
            formatProperty(lines, "", property);
        }
        for (MethodReference method : sortedMethods(getInstanceMethods(type))) {
            formatMethod(lines, "", method);
        }
        for (IndexOperation operation : type.getIndexOperations()) {
            lines.add(String.format("\t%s this[%s index] %s", formatType(operation.returnType), formatType(operation.indexType), formatGetSet(operation.canGet(), operation.canSet())));
        }
        for (UnaryOperation operation : type.getUnaryOperations()) {
            lines.add(String.format("\toperator [%s] %s(%s arg);", operation.getOperator(), formatType(operation.getResultType()), formatType(operation.getOperandType())));
        }
        for (BinaryOperation operation : type.getBinaryOperations()) {
            if (operation.getLeft() == SJavaObject.instance && operation.getRight() == SJavaObject.instance) {
                continue;
            }
            if (operation.getOperator() == BinaryOperator.NULL_COALESCING) {
                continue;
            }
            lines.add(String.format(
                    "\toperator [%s] %s(%s left, %s right);",
                    operation.getOperator(),
                    formatType(operation.getResultType()),
                    formatType(operation.getLeft()),
                    formatType(operation.getRight())));
        }

        if (type instanceof SClassType && javaClass != null) {
            for (Class<?> nested : javaClass.getDeclaredClasses()) {
                if (Modifier.isPublic(nested.getModifiers())) {
                    int start = lines.size();
                    buildType(lines, SType.fromJavaType(nested));
                    for (int i = start; i < lines.size(); i++) {
                        lines.set(i, "\t" + lines.get(i));
                    }
                }
            }
        }

        lines.add("}");
    }

    private static List<PropertyReference> sortedProperties(List<PropertyReference> properties) {
        return properties.stream().sorted(Comparator.comparing(PropertyReference::getName)).toList();
    }

    private static List<MethodReference> sortedMethods(List<MethodReference> methods) {
        return methods.stream().sorted(Comparator.comparing(MethodReference::getName).thenComparing(method -> method.getParameters().size())).toList();
    }

    private static List<PropertyReference> getStaticProperties(SType type) {
        return type.getDeclaredProperties().stream().filter(property -> property.getVisibility() == Visibility.PUBLIC).filter(MemberReference::isStatic).toList();
    }

    private static List<MethodReference> getStaticMethods(SType type) {
        return type.getDeclaredMethods().stream().filter(method -> method.getVisibility() == Visibility.PUBLIC).filter(MemberReference::isStatic).toList();
    }

    private static List<PropertyReference> getInstanceProperties(SType type) {
        return type.getDeclaredProperties().stream().filter(property -> property.getVisibility() == Visibility.PUBLIC).filter(property -> !property.isStatic()).toList();
    }

    private static List<MethodReference> getInstanceMethods(SType type) {
        return type.getDeclaredMethods().stream().filter(method -> method.getVisibility() == Visibility.PUBLIC).filter(method -> !method.isStatic()).toList();
    }

    private static void formatProperty(List<String> lines, String prefix, PropertyReference property) {
        formatDescription(lines, "\t", property.getDescription());
        lines.add(String.format("\t%s%s %s %s", prefix, formatType(property.getType()), property.getName(), formatGetSet(property.canLoad(), property.canStore())));
    }

    private static void formatMethod(List<String> lines, String prefix, MethodReference method) {
        formatDescription(lines, "\t", method.getDescription());
        if (method instanceof NativeMethodReference nativeMethod) {
            ApiVisibility visibility = nativeMethod.getUnderlying().getAnnotation(ApiVisibility.class);
            if (visibility != null) {
                lines.add(String.format("\t@ApiVisibility(%s)", String.join(", ", Arrays.stream(visibility.value()).map(ApiType::name).toList())));
            }
        }
        lines.add(String.format("\t%s%s %s(%s);", prefix, formatType(method.getReturn()), method.getName(), formatParameters(method.getParameters())));
    }

    private static void formatDescription(List<String> lines, String indent, Optional<String> description) {
        description.ifPresent(value -> {
            String[] values = extractLines(value);
            if (values.length == 1) {
                lines.add(String.format("%s/* %s */", indent, values[0]));
            } else {
                lines.add(indent + "/*");
                for (String line : values) {
                    lines.add(String.format("%s* %s", indent, line));
                }
                lines.add(indent + "*/");
            }
        });
    }

    private static String formatParameters(List<MethodParameter> parameters) {
        StringJoiner joiner = new StringJoiner(", ");
        for (MethodParameter parameter : parameters) {
            joiner.add(formatType(parameter.type()) + " " + parameter.name());
        }
        return joiner.toString();
    }

    private static String formatType(SType type) {
        return TYPE_FORMATTER.format(type);
    }

    private static boolean shouldIncludeConstructors(SType type) {
        if (type instanceof SClassType classType) {
            return !classType.getJavaClass().getPackageName().startsWith("com.zergatul.cheatutils.scripting.api.modules");
        }
        return true;
    }

    private static List<SType> getPrimitiveTypes() {
        return List.of(SBoolean.instance, SInt8.instance, SInt16.instance, SInt.instance, SInt64.instance, SFloat32.instance, SFloat.instance, SChar.instance, SString.instance);
    }

    private static String formatGetSet(boolean canGet, boolean canSet) {
        if (canGet && canSet) {
            return "{ get; set; }";
        }
        if (canGet) {
            return "{ get; }";
        }
        if (canSet) {
            return "{ set; }";
        }
        return "<error>";
    }

    private static String[] extractLines(String value) {
        return value.split("\\r?\\n");
    }

    private ApiDocsGenerator() {}
}