name: Build

on:
  push:
    branches: ['1.12.2']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@main
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@main
        with:
          distribution: temurin
          java-version: 8

      - name: Build
        run: ./gradlew build

      - name: Upload Artifacts
        uses: actions/upload-artifact@main
        with:
          name: forge
          path: build/libs/*.jar
          compression-level: 0
          if-no-files-found: error