name: Build

on:
  push:
    branches:
      - '26.[1-9]'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@main
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@main
        with:
          distribution: temurin
          java-version: 25

      - name: Build
        run: |
          cd universal
          ./gradlew universalJar -Ploaders=fabric

      - name: Create CurseForge build
        shell: pwsh
        run: Get-ChildItem ./universal/build/libs/*.jar | ./scripts/ConvertTo-CurseForgeBuild.ps1

      - name: Upload Artifacts
        uses: actions/upload-artifact@main
        with:
          name: universal
          path: universal/build/libs/*.jar
          compression-level: 0
          if-no-files-found: error