name: Build

on:
  push:
    branches:
      - '1.20.[0-9]'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@main
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@main
        with:
          distribution: temurin
          java-version: 17

      - name: Build Forge
        run: |
          pushd ./forge
          chmod +x ./gradlew
          ./gradlew build
          popd

      - name: Build Fabric
        run: |
          pushd ./fabric
          chmod +x ./gradlew
          ./gradlew build
          popd

      - name: Upload Forge artifacts
        uses: actions/upload-artifact@main
        with:
          name: forge
          path: ./forge/build/libs/*.jar
          compression-level: 0
          if-no-files-found: error

      - name: Upload Fabric artifacts
        uses: actions/upload-artifact@main
        with:
          name: fabric
          path: ./fabric/build/libs/*.jar
          compression-level: 0
          if-no-files-found: error