name: Build

on:
  push:
    branches:
      - '26.[1-9]-dev'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 25

      - name: Build Forge
        run: |
          pushd ./forge
          chmod +x ./gradlew
          ./gradlew build
          popd

      - name: Build Fabric
        run: |
          pushd ./fabric
          chmod +x ./gradlew
          ./gradlew build
          popd

      - name: Build NeoForge
        run: |
          pushd ./neoforge
          chmod +x ./gradlew
          ./gradlew build
          popd

      - name: Create CurseForge builds
        shell: pwsh
        run: |
          Get-ChildItem    ./forge/build/libs/*.jar | ./scripts/ConvertTo-CurseForgeBuild.ps1
          Get-ChildItem   ./fabric/build/libs/*.jar | ./scripts/ConvertTo-CurseForgeBuild.ps1
          Get-ChildItem ./neoforge/build/libs/*.jar | ./scripts/ConvertTo-CurseForgeBuild.ps1

      - name: Upload Forge artifacts
        uses: actions/upload-artifact@v4
        with:
          name: forge
          path: ./forge/build/libs/*.jar
          compression-level: 0
          if-no-files-found: error

      - name: Upload Fabric artifacts
        uses: actions/upload-artifact@v4
        with:
          name: fabric
          path: ./fabric/build/libs/*.jar
          compression-level: 0
          if-no-files-found: error

      - name: Upload NeoForge artifacts
        uses: actions/upload-artifact@v4
        with:
          name: neoforge
          path: ./neoforge/build/libs/*.jar
          compression-level: 0
          if-no-files-found: error